# Generated by Django 6.0.2 on 2026-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_cohort_professor_nomination_cohort_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='institution_name',
            field=models.CharField(default='Unknown Institution', max_length=255),
        ),
        migrations.AddField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
