# Generated by Django 6.0.2 on 2026-03-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cohort_institution_name_cohort_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='preferred_team_size',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
