# Generated by Django 6.0.2 on 2026-03-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_category_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
