# Generated by Django 6.0.2 on 2026-04-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notificationread_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_final_submission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.cohort')),
            ],
            options={
                'ordering': ['order_index', 'due_date'],
            },
        ),
    ]
