# Generated by Django 6.0.2 on 2026-04-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cohortmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='handbook',
            field=models.FileField(blank=True, null=True, upload_to='handbooks/'),
        ),
    ]
