# Generated by Django 6.0.2 on 2026-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_handbook_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_final_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
