# Generated by Django 6.0.2 on 2026-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_team_is_final_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
