# Generated by Django 6.0.2 on 2026-04-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_evaluation_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortmembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='access_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
