# Generated by Django 6.0.2 on 2026-04-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cohortmembership_status_user_access_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortmembership',
            name='access_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
