# Generated by Django 6.0.2 on 2026-05-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_team_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.team'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('ALL', 'All Users'), ('PROFESSORS', 'Professors Only'), ('LEARNERS', 'Learners Only'), ('COHORT', 'Specific Cohort'), ('TEAM', 'Specific Team')], default='ALL', max_length=20),
        ),
    ]
